services:
  ollama-cpu:
    ports:
      - 127.0.0.1:11434:11434

  ollama-gpu:
    ports:
      - 127.0.0.1:11434:11434

  ollama-gpu-amd:
    ports:
      - 127.0.0.1:11434:11434

  comfyui-cpu:
    ports:
      - 127.0.0.1:8188:8188

  comfyui-gpu:
    ports:
      - 127.0.0.1:8188:8188

  comfyui-gpu-amd:
    ports:
      - 127.0.0.1:8188:8188
